// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLu6_cdjJdl9-zWICD5ko3-c86dCeIX2M',
    appId: '1:1922524282:web:fe840dca5c8144f97e87c3',
    messagingSenderId: '1922524282',
    projectId: 'vfs-dynamic-app',
    authDomain: 'vfs-dynamic-app.firebaseapp.com',
    storageBucket: 'vfs-dynamic-app.appspot.com',
    measurementId: 'G-16W2NZWQ04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx7d4KDTgef4q5CFSKtO6LAOuScI7iFMo',
    appId: '1:1922524282:android:a973d672a1cc36847e87c3',
    messagingSenderId: '1922524282',
    projectId: 'vfs-dynamic-app',
    storageBucket: 'vfs-dynamic-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI4uSxQy3osELyaHiRji8oF_0TQv1G1M0',
    appId: '1:1922524282:ios:d4ced27d03cf98837e87c3',
    messagingSenderId: '1922524282',
    projectId: 'vfs-dynamic-app',
    storageBucket: 'vfs-dynamic-app.appspot.com',
    iosBundleId: 'com.example.vfsDynamicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI4uSxQy3osELyaHiRji8oF_0TQv1G1M0',
    appId: '1:1922524282:ios:d4ced27d03cf98837e87c3',
    messagingSenderId: '1922524282',
    projectId: 'vfs-dynamic-app',
    storageBucket: 'vfs-dynamic-app.appspot.com',
    iosBundleId: 'com.example.vfsDynamicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLu6_cdjJdl9-zWICD5ko3-c86dCeIX2M',
    appId: '1:1922524282:web:36758225d801621c7e87c3',
    messagingSenderId: '1922524282',
    projectId: 'vfs-dynamic-app',
    authDomain: 'vfs-dynamic-app.firebaseapp.com',
    storageBucket: 'vfs-dynamic-app.appspot.com',
    measurementId: 'G-0ZMPM8FGD2',
  );
}
